name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build --if-present
      env:
        CI: true
    - run: git config --global user.email "42261670+nashenol@users.noreply.github.com"
      if: contains(github.ref, "master")
    - run: git config --global user.name "nashenol"
      if: contains(github.ref, "master")
    - run: npm run deploy
      if: contains(github.ref, 'master')
